---
name: guacamole
version: 1.0.1
stage: stable
slug: guacamole
description: >-
  Guacamole Remote Management boxed in a HA AddOn
url: https://github.com/rolbre/hassio-addons/tree/main/guacamole
arch:
  - amd64
codenotary: breitschaftroland@gmail.com
host_network: false
startup: services
init: false
advanced: true
apparmor: true
homeassistant: 2022.11.0
panel_admin: true
backup: hot
video: true
services:
  - mysql:want
map:
  - config:rw
ports:
  8080/tcp: 8080
options:
  log_level: info
schema:
  use_database: bool?
  reset_database: bool?
  database_password: password?
  use_totp: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
