---
name: matrix
version: 0.1.2
stage: experimental
slug: matrix
description: >-
  An open network for secure, decentralized communication boxed in a HA AddOn
url: https://github.com/rolbre/hassio-addons/tree/main/matrix
arch:
  - amd64
codenotary: breitschaftroland@gmail.com
host_network: false
startup: services
init: false
advanced: true
apparmor: true
homeassistant: 2022.11.0
panel_admin: true
backup: hot
map:
  - config:rw
  - share:rw
ports:
  8008/tcp: 8008
  8448/tcp: 8448
options:
  log_level: info
schema:
  server_name: str
  report_stats: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
